deleted:    BLDLIBDWARF 	deleted:    CLEANUP 	deleted:    CPTOPUBLIC 	modified:   Makefile.in 	deleted:    REBLDLIBDWARF 	new file:   scripts/BLDLIBDWARF 	renamed:    BLDLIBDWARFTAR -> scripts/BLDLIBDWARFTAR 	renamed:    BLDTESTDIR -> scripts/BLDTESTDIR 	new file:   scripts/CLEANUP 	new file:   scripts/CPTOPUBLIC 	renamed:    CREATINGARELEASE -> scripts/CREATINGARELEASE 	new file:   scripts/REBLDLIBDWARF 	renamed:    SETUP_MASTER_TREE -> scripts/SETUP_MASTER_TREE 	renamed:    UPD.awk -> scripts/UPD.awk 	renamed:    UPDATEDWARFDUMPVERSION.sh -> scripts/UPDATEDWARFDUMPVERSION.sh
This action moves the miscellaneous scripts
into the directory 'scripts'.
None of these are needed except by the
maintainers.

diff --git a/scripts/BLDLIBDWARFTAR b/scripts/BLDLIBDWARFTAR
--- a/scripts/BLDLIBDWARFTAR
+++ b/scripts/BLDLIBDWARFTAR
@@ -2,6 +2,48 @@
 #
 #newpref sets directory name with date, more
 #like normal linux packages.
+l=`pwd`
+echo $l
+lb=`basename $l`
+ld=`dirname $l`
+#echo " lb: $lb"
+#echo " ld: $ld"
+cdtarg=.
+sloc=$l/scripts
+if [ x$lb = "xscripts" ]
+then
+  #echo "ld: $ld"
+  ldb=`basename $ld`
+  #echo "ldb: $ldb"
+  if [ x$ldb = "xcode" ]
+  then
+     cdtarg=..
+     sloc=$l
+  else
+     echo "Run from */code, not $l , giving up."
+     exit 1
+  fi
+  cd $cdtarg
+  if [ $? -ne 0 ]
+  then
+     echo "cd $cdtarg failed, giving up."
+     exit 1
+  fi
+else
+  if [ x$lb = "xcode" ]
+  then
+    cdtarg="."
+  else
+    echo "Run from */code, not $l , giving up."
+    exit 1
+  fi
+  # No need to cd.
+fi
+l=`pwd`
+#echo "Now at $l"
+#echo "sloc $sloc"
+
+
 if [ $# != 1 ]
 then
 	echo  Usage: BLDLIBDWARFTAR yyyymmdd
@@ -17,7 +59,7 @@ dat=$1
 tmpf=dwarf
 tmpdir=/var/tmp
 # cptopublic knows /var/tmp/dwarf is the target
-sh CPTOPUBLIC nouv 
+sh $sloc/CPTOPUBLIC nouv 
 newpref=dwarf-${dat}
 newf=libdwarf-${dat}.tar
 echo src is $tmpdir/$tmpf tmp is $newpref target is $newf
